// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDph93_h0bDU2qz0oFRlt9h_nF_jM55mjE',
    appId: '1:1086961716031:web:1dddd781c9895a9fb9218a',
    messagingSenderId: '1086961716031',
    projectId: 'attendee-cedc2',
    authDomain: 'attendee-cedc2.firebaseapp.com',
    storageBucket: 'attendee-cedc2.firebasestorage.app',
    measurementId: 'G-3KSSQX0SEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQOtXEbH62IDkAmrX-bmjTRzakXGlu370',
    appId: '1:1086961716031:android:2d86cae4185db244b9218a',
    messagingSenderId: '1086961716031',
    projectId: 'attendee-cedc2',
    storageBucket: 'attendee-cedc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhbFuVKobwGrG-bXMqfpAaX9mPDDTaoQ',
    appId: '1:1086961716031:ios:64172ab038a7190fb9218a',
    messagingSenderId: '1086961716031',
    projectId: 'attendee-cedc2',
    storageBucket: 'attendee-cedc2.firebasestorage.app',
    iosBundleId: 'com.example.attendee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEhbFuVKobwGrG-bXMqfpAaX9mPDDTaoQ',
    appId: '1:1086961716031:ios:64172ab038a7190fb9218a',
    messagingSenderId: '1086961716031',
    projectId: 'attendee-cedc2',
    storageBucket: 'attendee-cedc2.firebasestorage.app',
    iosBundleId: 'com.example.attendee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDph93_h0bDU2qz0oFRlt9h_nF_jM55mjE',
    appId: '1:1086961716031:web:a3f55b78be7eef97b9218a',
    messagingSenderId: '1086961716031',
    projectId: 'attendee-cedc2',
    authDomain: 'attendee-cedc2.firebaseapp.com',
    storageBucket: 'attendee-cedc2.firebasestorage.app',
    measurementId: 'G-S8ZKKL5VSD',
  );
}
